pipeline {
    agent { label 'Slave_A' }

    environment {
        IMAGE_NAME = "vasundharadp/app"
        CONTAINER_NAME = "app_container"
    }

    stages {

        stage('Pull Latest Image') {
            steps {
                sh "docker pull ${IMAGE_NAME}:latest"
            }
        }

        stage('Stop Old Container') {
            steps {
                sh "docker stop ${CONTAINER_NAME} || true"
                sh "docker rm ${CONTAINER_NAME} || true"
            }
        }

        stage('Run New Container') {
            steps {
                sh "docker run -d -p 3000:3000 --name ${CONTAINER_NAME} ${IMAGE_NAME}:latest"
            }
        }
    }
}
